### ISSUE TITLE
finalize May meetup

### ISSUE THREAD

**Issue by loudermilk** [loudermilk/nwa-data-science#10]
@cmstewart will you update ticket with meetup details incl. abstract.

**Comment by cmstewart** [comment]
sure. as soon as I hear something back from our speakers, I'll put it here.

**Comment by loudermilk** [comment]
yo dawg, what's the status? Let's try and get an initial announcement out by end of week... even just a title will work.

**Comment by cmstewart** [comment]
you've seen the email exchanges. I have probably asked >5 times for more info. emailed them again this morning. maybe we should come up with a backup plan?

**Comment by loudermilk** [comment]
thnx chris, this looks like its gonna be an awesome talk.

**Comment by cmstewart** [comment]
yeah, let's hope so! it has definitely been a bit more work than the others to set up, but hopefully it'll be worth it...
