### ISSUE TITLE
post pics from May meetup

### ISSUE THREAD

**Issue by loudermilk** [loudermilk/nwa-data-science#13]
@freshforlife @cmstewart - please post on meetup (mine suck)

**Comment by cmstewart** [comment]
@loudermilk -- can you make a photo album for the last meetup? I don't have permissions.

**Comment by freshforlife** [comment]
I will do that, i.e. make an album.

**Comment by loudermilk** [comment]
@freshforlife thanks.

**Comment by loudermilk** [comment]
done next
