### ISSUE TITLE
Brainstorm next event (June/July)

### ISSUE THREAD

**Issue by loudermilk** [loudermilk/nwa-data-science#14]
@freshforlife @MarkRConway @cmstewart - please post any ideas here... let's have a discussion early next week

**Comment by mrconway** [comment]
Maybe we can try John Fox again?

**Comment by loudermilk** [comment]
@cmstewart is going to contact Tom about doing a data viz talk.

**Comment by cmstewart** [comment]
done. will let you all know what I hear back.

**Comment by loudermilk** [comment]
Sent a msg: 

> Hi Tom - hope you are enjoying your summer! You expressed interest awhile back about doing a data viz talk --  can we schedule you for a presentation in July? I know that I and several of my colleagues would love to get a fresh perspective on the latest trends in data viz... let me know what you think. Thanks, ~Brandon

**Comment by loudermilk** [comment]
July 26 at Lofty Labs, speaker Dr. Mike Gashler, UofA  (**chris, do we have a time?**)

Neural networks can be surprisingly flexible models. For example, it is well known that artificial neural networks can be differentiated to compute a gradient useful for updating their weights, but it is somewhat lesser known that they can also be differentiated with respect to their inputs. This property enables one to infer latent inputs that are useful in a variety of non-traditional roles, such as non-linear dimensionality reduction, missing value imputation, and collaborative filtering recommender systems. This talk will discuss latent inputs and some other techniques that can be used for making neural networks suitable for applications like time series prediction and robot control.

**Comment by cmstewart** [comment]
Yeah, Brandon, we're on for 7 PM.

**Comment by loudermilk** [comment]
I will put together a quick bio and then post the initial announcement today.
