### ISSUE TITLE
August Event

### ISSUE THREAD

**Issue by loudermilk** [loudermilk/nwa-data-science#16]
Tom from TCS is interested...

**Comment by loudermilk** [comment]
posted note on walmart slack to see if anybody is interested...

**Comment by loudermilk** [comment]
no response back from WMT people (but I'm not holding my breath)... @roboman90 do you want to meet up today or tmrw to talk shop? If not, we can all meet up early next week so we can include @cmstewart and @MarkRConway .

**Comment by ghost** [comment]
Hey Brandon, 

We can definitely meet for lunch today if you want. Do you have a place in mind? 

Bowen

**Comment by loudermilk** [comment]
sorry bowen didn't see your reply until now (I guess my alerts aren't working), and I just finished lunch.

Anyway given my own interests in data viz and perceptual processing, I sent the following email: to this person -- http://cs.okstate.edu/~etemadp/

Let's see what she says... if not interested we can pursue other options.

> Dear Dr. Etemadpour,
> I hope you are enjoying your summer. My name is Brandon Loudermilk and I am a software engineer and data scientist working in Bentonville, AR. My colleagues and I run the NWA Data Science meetup - a recently formed interest group for big data, analytics, machine learning, and data visualization. 
> 
> Your research on multidimensional visualization sounds fascinating and I am particularly interested in your use of eye-tracking to measure perceptual processing of visually displayed quantitative information. We are currently in the process of organizing our next event and I am reaching out to see if you or one of your graduate students would be interested in presenting their research to our group. 
> 
> We typically host our events on a weekday evening (in Bentonville or Fayetteville) and have about 50 attendees on average. We are hoping to organize an event later this month or early September.
> 
> If you or one of your grad students is interested in giving a talk, please get in contact with me (b.c.loudermilk@gmail.com 530-304-6327) or our event coordinator Dr. Chris Stewart  (stewart.christophermichael@gmail.com).

**Comment by cmstewart** [comment]
looks like a good candidate! really disappointing that we can't get someone from WM. a biz talk would be a welcome change from our usual more technical subjects. oh well...

**Comment by ghost** [comment]
We can meet anytime, no worries. I'm flexible since I'm still unemployed.
Lol.

Just reached back out to the engineering association at Yale, see if they
have anybody with serious research or work background that wants to share
with our group. It's long shot, but worth a try.

**Comment by loudermilk** [comment]
Also, Pejman is doing some stuff with TensorFlow -- somethings about image classification of political photos... said he'd be willing to do a workshop or something.

**Comment by loudermilk** [comment]
also some interest in doing a newbie Q&A or workshop - http://www.meetup.com/NWA-Data-Science-Meetup/boards/view/viewthread?thread=50037012

**Comment by loudermilk** [comment]
^^ I think maybe we need to send out a poll to see how many are interested (on both sides) as our message board gets very little traffic

**Comment by cmstewart** [comment]
good idea, I suppose. I think that if we could get a business person, it might make it a bit easier to approach for newbies. just a thought.

**Comment by ghost** [comment]
We could also have attendees share some of their work and thoughts, maybe after the main presentation, to stimulate conversations within the group. People are more likely to come if they are able to mingle well with others in the group. It's also conceivable that they will invite others they know to watch their short sharing session after the main presentation.

**Comment by loudermilk** [comment]
set to go, thanks bowen:

> Wednesday, August 31, 2016
> 7:00 PM
> 
> Tata Consultancy Services (across from Walmart home office)
> 609 SW 8th St. (9th floor), Bentonville, AR (edit map)
> 
> This is a information session for professionals to share their experience and take questions from people that are interested in data science. 
> 
> A tentative meetup schedule is as follows:
> 1. 10min introduction of professionals (1-3min each) 
> 2. 35min Q&A session. Open up the floor to audience. 
> 3. Break up in groups to mingle till we finish the event.  
> 
> If you are interested in sharing as a professional, please contact Bowen at bowengongi@gmail.com or message him on linkedin.

**Comment by loudermilk** [comment]
Event publicity:
[ ] linkedin
[ ] twitter
[ ] G+

To dos:
[ ] light snacks
[ ] soda, drinks
[ ] sign in sheet
[ ] volunteers to man downstairs doors

**Comment by loudermilk** [comment]
@roboman90 -- how does this read for a linkedin post? 

> Are you interested in data science and analytics? Do you want to network with some of the best analytic talent in Northwest Arkansas? Are you looking for collaborators for your latest venture? Then come join NWA Data Science!
> 
> NWA Data Science is pleased to announce an information session for analytics professionals to share their experience and take questions from people interested in the field. This informal “meet and greet” style event will be held on Wednesday, August 31 starting at 7pm in the TCS offices across the street from the Walmart Home Office. Light refreshments will be served. For more information visit and directions: http://www.meetup.com/NWA-Data-Science-Meetup/events/233492609/

**Comment by ghost** [comment]
Sounds more lively than the email I sent out. Lol.
